# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/Work/singly_linked_list

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/Work/singly_linked_list

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Work/singly_linked_list/CMakeFiles /home/david/Work/singly_linked_list/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Work/singly_linked_list/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SinglyLinkedListLibrary_UnitTest

# Build rule for target.
SinglyLinkedListLibrary_UnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SinglyLinkedListLibrary_UnitTest
.PHONY : SinglyLinkedListLibrary_UnitTest

# fast build rule for target.
SinglyLinkedListLibrary_UnitTest/fast:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build
.PHONY : SinglyLinkedListLibrary_UnitTest/fast

#=============================================================================
# Target rules for targets named SinglyLinkedList

# Build rule for target.
SinglyLinkedList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SinglyLinkedList
.PHONY : SinglyLinkedList

# fast build rule for target.
SinglyLinkedList/fast:
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/build
.PHONY : SinglyLinkedList/fast

LinkedListFileParser.o: LinkedListFileParser.cpp.o

.PHONY : LinkedListFileParser.o

# target to build an object file
LinkedListFileParser.cpp.o:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/LinkedListFileParser.cpp.o
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/LinkedListFileParser.cpp.o
.PHONY : LinkedListFileParser.cpp.o

LinkedListFileParser.i: LinkedListFileParser.cpp.i

.PHONY : LinkedListFileParser.i

# target to preprocess a source file
LinkedListFileParser.cpp.i:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/LinkedListFileParser.cpp.i
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/LinkedListFileParser.cpp.i
.PHONY : LinkedListFileParser.cpp.i

LinkedListFileParser.s: LinkedListFileParser.cpp.s

.PHONY : LinkedListFileParser.s

# target to generate assembly for a file
LinkedListFileParser.cpp.s:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/LinkedListFileParser.cpp.s
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/LinkedListFileParser.cpp.s
.PHONY : LinkedListFileParser.cpp.s

LinkedListFileParserAcceptanceTest.o: LinkedListFileParserAcceptanceTest.cpp.o

.PHONY : LinkedListFileParserAcceptanceTest.o

# target to build an object file
LinkedListFileParserAcceptanceTest.cpp.o:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/LinkedListFileParserAcceptanceTest.cpp.o
.PHONY : LinkedListFileParserAcceptanceTest.cpp.o

LinkedListFileParserAcceptanceTest.i: LinkedListFileParserAcceptanceTest.cpp.i

.PHONY : LinkedListFileParserAcceptanceTest.i

# target to preprocess a source file
LinkedListFileParserAcceptanceTest.cpp.i:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/LinkedListFileParserAcceptanceTest.cpp.i
.PHONY : LinkedListFileParserAcceptanceTest.cpp.i

LinkedListFileParserAcceptanceTest.s: LinkedListFileParserAcceptanceTest.cpp.s

.PHONY : LinkedListFileParserAcceptanceTest.s

# target to generate assembly for a file
LinkedListFileParserAcceptanceTest.cpp.s:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/LinkedListFileParserAcceptanceTest.cpp.s
.PHONY : LinkedListFileParserAcceptanceTest.cpp.s

SinglyLinkedList.o: SinglyLinkedList.cpp.o

.PHONY : SinglyLinkedList.o

# target to build an object file
SinglyLinkedList.cpp.o:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedList.cpp.o
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/SinglyLinkedList.cpp.o
.PHONY : SinglyLinkedList.cpp.o

SinglyLinkedList.i: SinglyLinkedList.cpp.i

.PHONY : SinglyLinkedList.i

# target to preprocess a source file
SinglyLinkedList.cpp.i:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedList.cpp.i
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/SinglyLinkedList.cpp.i
.PHONY : SinglyLinkedList.cpp.i

SinglyLinkedList.s: SinglyLinkedList.cpp.s

.PHONY : SinglyLinkedList.s

# target to generate assembly for a file
SinglyLinkedList.cpp.s:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedList.cpp.s
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/SinglyLinkedList.cpp.s
.PHONY : SinglyLinkedList.cpp.s

SinglyLinkedListAcceptanceTest.o: SinglyLinkedListAcceptanceTest.cpp.o

.PHONY : SinglyLinkedListAcceptanceTest.o

# target to build an object file
SinglyLinkedListAcceptanceTest.cpp.o:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListAcceptanceTest.cpp.o
.PHONY : SinglyLinkedListAcceptanceTest.cpp.o

SinglyLinkedListAcceptanceTest.i: SinglyLinkedListAcceptanceTest.cpp.i

.PHONY : SinglyLinkedListAcceptanceTest.i

# target to preprocess a source file
SinglyLinkedListAcceptanceTest.cpp.i:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListAcceptanceTest.cpp.i
.PHONY : SinglyLinkedListAcceptanceTest.cpp.i

SinglyLinkedListAcceptanceTest.s: SinglyLinkedListAcceptanceTest.cpp.s

.PHONY : SinglyLinkedListAcceptanceTest.s

# target to generate assembly for a file
SinglyLinkedListAcceptanceTest.cpp.s:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListAcceptanceTest.cpp.s
.PHONY : SinglyLinkedListAcceptanceTest.cpp.s

SinglyLinkedListLibrary.o: SinglyLinkedListLibrary.cpp.o

.PHONY : SinglyLinkedListLibrary.o

# target to build an object file
SinglyLinkedListLibrary.cpp.o:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListLibrary.cpp.o
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/SinglyLinkedListLibrary.cpp.o
.PHONY : SinglyLinkedListLibrary.cpp.o

SinglyLinkedListLibrary.i: SinglyLinkedListLibrary.cpp.i

.PHONY : SinglyLinkedListLibrary.i

# target to preprocess a source file
SinglyLinkedListLibrary.cpp.i:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListLibrary.cpp.i
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/SinglyLinkedListLibrary.cpp.i
.PHONY : SinglyLinkedListLibrary.cpp.i

SinglyLinkedListLibrary.s: SinglyLinkedListLibrary.cpp.s

.PHONY : SinglyLinkedListLibrary.s

# target to generate assembly for a file
SinglyLinkedListLibrary.cpp.s:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListLibrary.cpp.s
	$(MAKE) -f CMakeFiles/SinglyLinkedList.dir/build.make CMakeFiles/SinglyLinkedList.dir/SinglyLinkedListLibrary.cpp.s
.PHONY : SinglyLinkedListLibrary.cpp.s

SinglyLinkedListLibraryAcceptanceTest.o: SinglyLinkedListLibraryAcceptanceTest.cpp.o

.PHONY : SinglyLinkedListLibraryAcceptanceTest.o

# target to build an object file
SinglyLinkedListLibraryAcceptanceTest.cpp.o:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListLibraryAcceptanceTest.cpp.o
.PHONY : SinglyLinkedListLibraryAcceptanceTest.cpp.o

SinglyLinkedListLibraryAcceptanceTest.i: SinglyLinkedListLibraryAcceptanceTest.cpp.i

.PHONY : SinglyLinkedListLibraryAcceptanceTest.i

# target to preprocess a source file
SinglyLinkedListLibraryAcceptanceTest.cpp.i:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListLibraryAcceptanceTest.cpp.i
.PHONY : SinglyLinkedListLibraryAcceptanceTest.cpp.i

SinglyLinkedListLibraryAcceptanceTest.s: SinglyLinkedListLibraryAcceptanceTest.cpp.s

.PHONY : SinglyLinkedListLibraryAcceptanceTest.s

# target to generate assembly for a file
SinglyLinkedListLibraryAcceptanceTest.cpp.s:
	$(MAKE) -f CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/build.make CMakeFiles/SinglyLinkedListLibrary_UnitTest.dir/SinglyLinkedListLibraryAcceptanceTest.cpp.s
.PHONY : SinglyLinkedListLibraryAcceptanceTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SinglyLinkedListLibrary_UnitTest"
	@echo "... SinglyLinkedList"
	@echo "... LinkedListFileParser.o"
	@echo "... LinkedListFileParser.i"
	@echo "... LinkedListFileParser.s"
	@echo "... LinkedListFileParserAcceptanceTest.o"
	@echo "... LinkedListFileParserAcceptanceTest.i"
	@echo "... LinkedListFileParserAcceptanceTest.s"
	@echo "... SinglyLinkedList.o"
	@echo "... SinglyLinkedList.i"
	@echo "... SinglyLinkedList.s"
	@echo "... SinglyLinkedListAcceptanceTest.o"
	@echo "... SinglyLinkedListAcceptanceTest.i"
	@echo "... SinglyLinkedListAcceptanceTest.s"
	@echo "... SinglyLinkedListLibrary.o"
	@echo "... SinglyLinkedListLibrary.i"
	@echo "... SinglyLinkedListLibrary.s"
	@echo "... SinglyLinkedListLibraryAcceptanceTest.o"
	@echo "... SinglyLinkedListLibraryAcceptanceTest.i"
	@echo "... SinglyLinkedListLibraryAcceptanceTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

